spring.application.name=lost-and-found-manager

   spring.datasource.url=jdbc:mysql://localhost:3306/lost_and_found
   spring.datasource.username=root
   spring.datasource.password=jaijaganO!O/mysql
   spring.jpa.hibernate.ddl-auto=update
